### ISSUE TITLE
多卡训练显卡利用率0%，训练很慢

### ISSUE THREAD

**Issue by DuZzzs** [xinzhuma/monodle#1]
您好，感谢您的优秀工作。我在跑代码的过程中遇到了以下几个问题。
1. 测试预训练模型时，readme中的预训练模型是多卡训练的，单卡测试会报错。解决办法：在`monodle/lib/helpers/save_helper.py:32` 加入：
```
    model = torch.nn.DataParallel(model).cuda()  # 强制让模型多卡
```
2. 训练时，`self.stats['train'] = {}`这里会报错。解决办法：在`amonodle/lib/helpers/trainer_helper.py:90`前面加入`self.stats={}`。
3. 2080ti上，2块卡训练，batch_size=16，显卡利用率大部分时间是0%，训练很慢。在代码中没看到您用torch的Dataloader，不清楚怎么加num_workers。请问有遇到类似的问题吗？谢谢

**Comment by Owen-Liuyuxuan** [comment]
2. 我好想没在其他代码里面看到self.stats的使用，我直接删了好像也可以?
3. dataloader_helper.py #12 里面 build_dataloader的default arguments里面有num_workers.

**Comment by DuZzzs** [comment]
> 1. 我好想没在其他代码里面看到self.stats的使用，我直接删了好像也可以?
> 2. dataloader_helper.py #12 里面 build_dataloader的default arguments里面有num_workers.

3. 谢谢。尝试了workers=4,8,16,和pin_memory=False，没观察到明显提升，还是几乎为0%。

**Comment by DuZzzs** [comment]
换成单卡训练，利用率95%以上。

**Comment by xinzhuma** [comment]
1. 感谢指出这个问题，对于目前提供的checkpoint，可以通过上述提到的方法测试。稍后我们会提供一个新的pre-train model并修改代码。
2. self.stats={}这个是我们之前用于统计/观测一些中间量用的，在开源时没有清除干净-。- 在这份代码里是没有作用的，像@Owen-Liuyuxuan说的那样直接删掉即可
3. 感谢@Owen-Liuyuxuan帮忙回答

**Comment by DuZzzs** [comment]
您好，单卡，batch_size=8，eval结果：
```
2021-06-18 09:58:45,895   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:96.7482, 88.8430, 80.0103
bev  AP:22.5176, 18.8652, 17.8965
3d   AP:15.6267, 13.0623, 12.5833
aos  AP:95.92, 87.98, 78.49
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.7721, 92.2750, 84.7456
bev  AP:20.8357, 16.9403, 14.7321
3d   AP:14.5454, 11.4979, 10.3641
aos  AP:96.91, 91.30, 82.90
Car AP@0.70, 0.50, 0.50:
bbox AP:96.7482, 88.8430, 80.0103
bev  AP:55.3472, 42.5173, 40.5583
3d   AP:51.7357, 40.4170, 38.3887
aos  AP:95.92, 87.98, 78.49
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.7721, 92.2750, 84.7456
bev  AP:54.6429, 42.3668, 38.3555
3d   AP:50.2907, 38.9975, 35.0315
aos  AP:96.91, 91.30, 82.90
```
3d   AP:14.5454, 11.4979, 10.3641， 和readme 



17.94 | 13.72 | 12.10
-- | -- | --




差了些。请问有可能是什么原因呢？谢谢

**Comment by xinzhuma** [comment]
@DuZzzs 会有些浮动 但是不应该这么大。 另外你的多卡情况也有些奇怪，我重新测试了一下也没发现你说的问题，可能是环境适配问题。我稍微调整了一下默认设置，你可以重新试试多卡训练。

**Comment by DuZzzs** [comment]
@xinzhuma 多卡问题应该是我没有配置slurm，没用slurm_train.sh，而用train.sh导致的。
