### ISSUE TITLE
How do I conduct the experiments in Table 1 mentioned in the paper?

### ISSUE THREAD

**Issue by sjg02122** [xinzhuma/monodle#10]
How do I conduct the experiments in Table 1 mentioned in the paper?

I change the below code 
but The result is so bad.

How can I  get the Table 1 result?

Code:
```
def evaluate(label_path,
             result_path,
             label_split_file,
             current_class=0,
             coco=False,
             score_thresh=-1):
    dt_annos = kitti.get_label_annos(result_path)
    if score_thresh > 0:
        dt_annos = kitti.filter_annos_low_score(dt_annos, score_thresh)
    val_image_ids = _read_imageset_file(label_split_file)
    gt_annos = kitti.get_label_annos(label_path, val_image_ids)
    dt_annos = kitti.get_label_annos(label_path, val_image_ids)
    if coco:
        return get_coco_eval_result(gt_annos, dt_annos, current_class)
    else:
        return get_official_eval_result(gt_annos, dt_annos, current_class)
```

Result:
2021-08-13 18:43:24,476   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0865, 0.1172, 0.2115
3d   AP:0.0865, 0.1172, 0.2115
aos  AP:100.00, 100.00, 100.00
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0238, 0.0322, 0.0582
3d   AP:0.0238, 0.0322, 0.0582
aos  AP:100.00, 100.00, 100.00
Car AP@0.70, 0.50, 0.50:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0865, 0.1172, 0.2115
3d   AP:0.0865, 0.1172, 0.2115
aos  AP:100.00, 100.00, 100.00
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.0238, 0.0322, 0.0582
3d   AP:0.0238, 0.0322, 0.0582
aos  AP:100.00, 100.00, 100.00

**Comment by xinzhuma** [comment]
For Table one, you need to replace the predicted items using GT values.
I don't know how you did it, but it seems that you only replace the 2D detection results and heading angle according to your results.

**Comment by sjg02122** [comment]
```
    def save_results(self, results, output_dir='./outputs'):
        output_dir = os.path.join(output_dir, 'data')
        os.makedirs(output_dir, exist_ok=True)

        for img_id in results.keys():
            if self.dataset_type == 'KITTI':
                output_path = os.path.join(output_dir, '{:06d}.txt'.format(img_id))
            else:
                os.makedirs(os.path.join(output_dir, self.dataloader.dataset.get_sensor_modality(img_id)), exist_ok=True)
                output_path = os.path.join(output_dir,
                                           self.dataloader.dataset.get_sensor_modality(img_id),
                                           self.dataloader.dataset.get_sample_token(img_id) + '.txt')

            f = open(output_path, 'w')
            for i in range(len(results[img_id])):
                class_name = self.class_name[int(results[img_id][i][0])]
                f.write('{} 0.0 0'.format(class_name))
                for j in range(1, len(results[img_id][i])):
                    f.write(' {:.2f}'.format(results[img_id][i][j]))
                f.write('\n')
            f.close()
```

I put the value of text file in the label folder instead of predicted value in the code above.
Is it right?

My question is whether the txt file created in the output folder and the txt of training - label_2 are the same files for replace predicted items using GT values.

**Comment by xinzhuma** [comment]
yes, the root/data/kitti/object/training/label_2/00****.txt is the GT file of the outputs/data/00****.txt.

**Comment by sjg02122** [comment]
It's my code 

```
    def save_results(self, results, output_dir='./outputs'):
        output_dir = os.path.join(output_dir, 'data')
        os.makedirs(output_dir, exist_ok=True)

        for img_id in results.keys():
            if self.dataset_type == 'KITTI':
                output_path = os.path.join(output_dir, '{:06d}.txt'.format(img_id))
            else:
                os.makedirs(os.path.join(output_dir, self.dataloader.dataset.get_sensor_modality(img_id)), exist_ok=True)
                output_path = os.path.join(output_dir,
                                           self.dataloader.dataset.get_sensor_modality(img_id),
                                           self.dataloader.dataset.get_sample_token(img_id) + '.txt')
            label_folder = '/home/cv1/hdd/monodle/data/KITTI/object/training/label_2/'
            label_file = label_folder + '{:06d}.txt'.format(img_id)
            lf = open(label_file,'r')
            lines = lf.readlines()
            temp =[]
            for i in lines:
                temp.append(i.strip().split(' '))
            labels =[]
            for i in temp:
                if(i[0]=='Car'):
                    labels.append(i)
            #replace predicted value using GT

            f = open(output_path,'w')
            for i in range(len(labels)):
                f.write('Car 0.0 0')
                for j in range(3,len(labels[i])):
                    f.write(' {:.2f}'.format(float(labels[i][j])))
                f.write(' 0.99') #for score
                f.write('\n')
            f.close()

            # f = open(output_path, 'w')
            # for i in range(len(results[img_id])):
            #     class_name = self.class_name[int(results[img_id][i][0])]
            #     f.write('{} 0.0 0'.format(class_name))
            #     for j in range(1, len(results[img_id][i])):
            #         f.write(' {:.2f}'.format(results[img_id][i][j]))
            #     f.write('\n')
            # f.close()
```

As far as I know, only the car is included in the predicted value. Therefore, after extracting only the values that correspond to Car from Label, 0.99 was added as the score value at the end.
Is it the right way I did it?
Using the above codes and eval, such as a result of the  2d is good, but 3d is not seems to be replaced.

**Comment by xinzhuma** [comment]
I am afraid there is something wrong with your script because I can't find any matching mechanism in your code.
Note that the predicted results don't have a line-to-line correspondence with GT items, even the number of objects are differents.
For example, the objects in the predicted file may [a, b, c,d], while these in GT file may [a, c, b].
You need to match your detections and GT objects first, and then replace the results.

**Comment by xinzhuma** [comment]
It seems you didn't replace anything. you just read the GT files and save it after adding 0.99 as the score.
Besides, you may also save the results in the wrong format. you can check is there any difference between your saved results and the original GT.

**Comment by sjg02122** [comment]
Thank you for your answer.
I understand that I need matching algorithm.
Then, if GT and the number of predicted files are different, which number did you match them to?

**Comment by xinzhuma** [comment]
You need to find the nearest GT for each predicted instance. As the result, the final number of instances should be the same as the results before item replacing.
Also, note to keep the score unchanged.

**Comment by sjg02122** [comment]
Ok, I understand.
Thank your kind answer.
I will try that.

**Comment by sjg02122** [comment]
As you told me, I matched each pre-predicted result with GT through matching algorithm. However, the problem is still unresolved.
First of all, I read the label file and printed out only GT that corresponds to the Car category.
Later, based on 2DBB, we matched the nearest GT and Predicted Objects.
The value of that Predicted Value was subsequently replaced by GT. 
Is there a problem in this process?
Thank you for your help.

Below are the results and codes that I used (save_result function in tester_helper.py).

```
def save_results(self, results, output_dir='./outputs'):
        output_dir = os.path.join(output_dir, 'data')
        os.makedirs(output_dir, exist_ok=True)

        for img_id in results.keys():
            if self.dataset_type == 'KITTI':
                output_path = os.path.join(output_dir, '{:06d}.txt'.format(img_id))
            else:
                os.makedirs(os.path.join(output_dir, self.dataloader.dataset.get_sensor_modality(img_id)), exist_ok=True)
                output_path = os.path.join(output_dir,
                                           self.dataloader.dataset.get_sensor_modality(img_id),
                                           self.dataloader.dataset.get_sample_token(img_id) + '.txt')
            print('*****************************{:06d}*****************************'.format(img_id))
            label_folder = '/home/cv1/hdd/monodle/data/KITTI/object/training/label_2/'
            label_file = label_folder + '{:06d}.txt'.format(img_id)
            lf = open(label_file,'r')
            lines = lf.readlines()
            temp =[]
            for i in lines:
                temp.append(i.strip().split(' '))
            labels =[]
            #################
            # 0: type
            # 1 : trucated
            # 2 : occluded
            # 3 : alpha
            # 4 : 2D left
            # 5 : 2D top
            # 6 : 2D right
            # 7 : 2D bottom
            # 8 : height
            # 9 : width
            # 10 : lenght
            # 11 : x
            # 12 : y
            # 13 : z
            # 14 : rotatio_y
            # 15 : score
            ################
            print('*****************************GT Value*****************************')
            gt_car = {}
            g_cnt=0

            for i in temp:
                labels.append(i)
                if(i[0]=='Car'):
                    # center_2d = ((float(i[6])-float(i[4]))/2 , (float(i[5])-float(i[7]))/2)
                    # i.append(center_2d)
                    gt_car[g_cnt]=i
                    g_cnt+=1
            
            for i in range(g_cnt):
                print(i,gt_car[i])
            # if(g_cnt==0):
            #     f = open(output_path, 'w')
            #     for i in range(len(results[img_id])):
            #         class_name = self.class_name[int(results[img_id][i][0])]
            #         f.write('{} 0.0 0'.format(class_name))
            #         print('{} 0.0 0'.format(class_name),end=' ')
            #         for j in range(1, len(results[img_id][i])):
            #             f.write(' {:.2f}'.format(results[img_id][i][j]))
            #             print(' {:.2f}'.format(results[img_id][i][j]),end=' ')
            #         f.write('\n')
            #         print()
            #     f.close()
            else:
            #replace predicted value using GT

            # f = open(output_path,'w')
            # for i in range(len(labels)):
            #     f.write('{} 0.0 0'.format(labels[i][0]))
            #     for j in range(3,len(labels[i])):
            #         f.write(' {:.2f}'.format(float(labels[i][j])))
            #     f.write(' 0.99') #for score
            #     f.write('\n')
            # f.close()
                def calc_distance(a,b):
                    ans =0
                    for i in range(1,2):
                        ans += abs(a[i]-float(b[i]))
                    return ans

                # print('*****************************Predicted Value*****************************')
                dt_car = []
                cnt=0
                for i in range(len(results[img_id])):
                    temp=[]
                    class_name = self.class_name[int(results[img_id][i][0])]
                    temp.append(class_name)
                    temp.append(0.0)
                    temp.append(0)
                    for j in range(1,len(results[img_id][i])):
                        temp.append(results[img_id][i][j])
                    dt_car.append(temp)

                obj_list=[]
                for i in range(len(dt_car)):
                    # center_2d = ((float(dt_car[i][6])-float(dt_car[i][4]))/2 , (float(dt_car[i][5])-float(dt_car[i][7]))/2)
                    # dt_car[i].append(center_2d)
                    # print(dt_car[i])
                    min_d = 1e12
                    obj_num = -1
                    for j in range(g_cnt):
                        if(j not in obj_list):
                            d = calc_distance(dt_car[i][3:-1],gt_car[j][3:])
                            if(min_d > d ):
                                obj_num = j
                                min_d = d
                    obj_list.append(obj_num)

                    # dt_car[i].pop()
                    if(obj_num != -1):
                        for k in range(3,len(dt_car[i])-1):
                            dt_car[i][k] = gt_car[obj_num][k]
                        # print(obj_num)
                    

                print('*****************************Refine Value*****************************')

                # for tmp in dt_car:
                #     print(tmp)
                
                f = open(output_path,'w')
                for i in range(len(dt_car)):
                    f.write('Car 0.0 0')
                    print("Car 0.0 0",end=' ')
                    for j in range(3,len(dt_car[i])-1):
                        f.write(' {:.2f}'.format(float(dt_car[i][j])))
                        print(' {:.2f}'.format(float(dt_car[i][j])),end=' ')
                    f.write(' {:.2f}'.format(dt_car[i][-1]))
                    print(' {:.2f}'.format(dt_car[i][-1]),end=' ')
                    f.write('\n')
                    print(i,'-->',obj_list[i],end='')
                    print()
                f.close()

            print('*****************************Predicted Save Value*****************************')
            # f = open(output_path, 'w')
            for i in range(len(results[img_id])):
                class_name = self.class_name[int(results[img_id][i][0])]
                # f.write('{} 0.0 0'.format(class_name))
                print('{} 0.0 0'.format(class_name),end=' ')
                for j in range(1, len(results[img_id][i])):
                    # f.write(' {:.2f}'.format(results[img_id][i][j]))
                    print(' {:.2f}'.format(results[img_id][i][j]),end=' ')
                # f.write('\n')
                print()
            # f.close()
            #input("Press the key to Next images")
```

Result (Some example):

*****************************006948*****************************

*****************************GT Value*****************************

0 ['Car', '0.32', '0', '2.16', '0.00', '184.67', '261.77', '370.54', '1.74', '1.65', '4.11', '-6.17', '1.90', '8.91', '1.57']

1 ['Car', '0.00', '0', '1.72', '490.79', '181.28', '545.61', '216.20', '1.41', '1.76', '4.40', '-3.99', '1.79', '31.76', '1.59']

2 ['Car', '0.00', '1', '1.97', '215.83', '184.95', '375.94', '274.09', '1.61', '1.64', '4.00', '-6.51', '1.89', '15.36', '1.58']

3 ['Car', '0.00', '2', '1.81', '384.32', '186.37', '456.81', '230.16', '1.43', '1.70', '3.74', '-6.84', '1.95', '26.27', '1.56']

4 ['Car', '0.00', '1', '-1.61', '629.28', '173.77', '657.31', '198.31', '1.55', '1.66', '4.15', '2.15', '1.64', '48.04', '-1.57']

5 ['Car', '0.00', '1', '2.95', '703.57', '164.65', '791.58', '192.02', '1.47', '1.70', '4.65', '7.74', '1.05', '40.97', '3.13']

6 ['Car', '0.00', '2', '2.98', '699.12', '159.11', '775.54', '191.80', '1.91', '1.81', '4.33', '7.70', '1.12', '44.04', '-3.13']

*****************************Refine Value*****************************

Car 0.0 0  1.97  215.83  184.95  375.94  274.09  1.61  1.64  4.00  -6.51  1.89  15.36  1.58  0.94 0 --> 2

Car 0.0 0  1.72  490.79  181.28  545.61  216.20  1.41  1.76  4.40  -3.99  1.79  31.76  1.59  0.89 1 --> 1

Car 0.0 0  2.16  0.00  184.67  261.77  370.54  1.74  1.65  4.11  -6.17  1.90  8.91  1.57  0.79 2 --> 0

Car 0.0 0  2.98  699.12  159.11  775.54  191.80  1.91  1.81  4.33  7.70  1.12  44.04  -3.13  0.68 3 --> 6

Car 0.0 0  -1.61  629.28  173.77  657.31  198.31  1.55  1.66  4.15  2.15  1.64  48.04  -1.57  0.55 4 --> 4

Car 0.0 0  1.81  384.32  186.37  456.81  230.16  1.43  1.70  3.74  -6.84  1.95  26.27  1.56  0.51 5 --> 3

Car 0.0 0  2.95  703.57  164.65  791.58  192.02  1.47  1.70  4.65  7.74  1.05  40.97  3.13  0.50 6 --> 5

Car 0.0 0  1.68  524.98  179.18  555.73  205.60  1.49  1.57  3.59  -4.21  1.90  43.73  1.58  0.32 7 --> -1

*****************************Predicted Save Value*****************************

Car 0.0 0  1.95  212.60  183.55  374.72  276.32  1.62  1.68  4.27  -6.41  1.86  14.99  1.55  0.94

Car 0.0 0  1.70  492.23  179.98  541.67  216.35  1.46  1.67  4.09  -4.11  1.80  32.12  1.57  0.89

Car 0.0 0  2.22  -12.71  176.49  264.56  364.09  1.76  1.57  3.91  -5.96  1.85  8.47  1.61  0.79

Car 0.0 0  2.82  694.78  163.65  787.19  194.95  1.55  1.68  4.42  6.76  1.12  37.83  3.00  0.68

Car 0.0 0  -1.53  628.37  174.68  656.68  198.18  1.48  1.65  3.96  2.17  1.62  47.86  -1.48  0.55

Car 0.0 0  1.75  469.98  181.56  507.66  208.33  1.48  1.63  3.94  -7.21  2.02  43.03  1.58  0.51

Car 0.0 0  1.83  392.47  186.25  454.83  227.35  1.44  1.52  3.45  -7.15  1.99  27.86  1.58  0.50

Car 0.0 0  1.68  524.98  179.18  555.73  205.60  1.49  1.57  3.59  -4.21  1.90  43.73  1.58  0.32



2021-08-14 22:16:32,252   INFO  Car AP@0.70, 0.70, 0.70:

bbox AP:99.0723, 90.5599, 90.2857

bev  AP:0.5146, 0.5146, 0.5146

3d   AP:0.5146, 0.5146, 0.5146

aos  AP:99.07, 90.56, 90.28

Car AP_R40@0.70, 0.70, 0.70:

bbox AP:99.6162, 96.8222, 94.2273

bev  AP:0.0248, 0.0344, 0.0591

3d   AP:0.0241, 0.0335, 0.0573

aos  AP:99.62, 96.82, 94.22

Car AP@0.70, 0.50, 0.50:

bbox AP:99.0723, 90.5599, 90.2857

bev  AP:0.5146, 0.5146, 0.5146

3d   AP:0.5146, 0.5146, 0.5146

aos  AP:99.07, 90.56, 90.28

Car AP_R40@0.70, 0.50, 0.50:

bbox AP:99.6162, 96.8222, 94.2273

bev  AP:0.0569, 0.0413, 0.1405

3d   AP:0.0552, 0.0396, 0.1344

aos  AP:99.62, 96.82, 94.22

**Comment by xinzhuma** [comment]
the main problem is the matching logic. the **distance**  should be the Euclidean distance of the center of samples in the 3D space.

**Comment by sjg02122** [comment]
I used a function to compare the distances between 3D locations for matching logic. 
But the problem is still unresolved.
```
            def distance(x1, y1, z1, x2, y2, z2):
                d = math.sqrt(math.pow(x2 - x1, 2) +math.pow(y2 - y1, 2) +math.pow(z2 - z1, 2)* 1.0)
                return d
```

you mean that3D space is not in camera coordinate? It's world coordinate?

**Comment by xinzhuma** [comment]
there may be some inappropriate logic in your script. For example,  in the following code:

                obj_list=[]
                for i in range(len(dt_car)):
                    # center_2d = ((float(dt_car[i][6])-float(dt_car[i][4]))/2 , (float(dt_car[i][5])-float(dt_car[i][7]))/2)
                    # dt_car[i].append(center_2d)
                    # print(dt_car[i])
                    min_d = 1e12
                    obj_num = -1
                    for j in range(g_cnt):
                        if(j not in obj_list):
                            d = calc_distance(dt_car[i][3:-1],gt_car[j][3:])
                            if(min_d > d ):
                                obj_num = j
                                min_d = d
                    obj_list.append(obj_num)

What's  the function of this line ？ ->:       **if(j not in obj_list):** 
It seems you only allow a GT match to one detection,  this is unreasonable.
For example, there is a results list:
GT: [[car, ..., ..., x=1, y=1, z=1]]
DT: [[car, ..., ..., x=10, y=10,z=10], [car, ..., ..., x=1.1, y=1.1, z=1.1] ]
According to your code, the GT will be assigned to detection1, instead of detection2. which is unreasonable. 
I just checked your code roughly, your need to check it carefully by yourself.

**Comment by sjg02122** [comment]
Thank you for your kind advice.
As you said, my matching algorithm had a problem.
I would like to match each of the 3D locations with a Hungarian algorithm by expressing the distances in graph for the right matching.

If you don't mind, could you simply tell me what the matching algorithm you used is?

**Comment by xinzhuma** [comment]
This is not bipartite graph matching, so the Hungarian algorithm is not okay. In the results, there may be several detections that describe the same GT. The NMS can't remove all redundant results. Besides, some GT instances may not be detected. So an easy implementation can be modified from your previous code:  (1)assign the most appropriate GT to each detected sample; (2) allowing that the GTs can be picked more than once; (3) using the 3D center distance in 3D space as metric.

**Comment by sjg02122** [comment]
Thanks a lot! I will try that.

**Comment by sjg02122** [comment]
I try to write the code by your advice, but The problem is still unsolved...
Can you share your code..? ( I write the command lines in my code but I can't understand what is the problem..) :(

My code :

    def save_results(self, results, output_dir='./outputs'):
        output_dir = os.path.join(output_dir, 'data')
        os.makedirs(output_dir, exist_ok=True)

        for img_id in results.keys():
            if self.dataset_type == 'KITTI':
                output_path = os.path.join(output_dir, '{:06d}.txt'.format(img_id))
            else:
                os.makedirs(os.path.join(output_dir, self.dataloader.dataset.get_sensor_modality(img_id)), exist_ok=True)
                output_path = os.path.join(output_dir,
                                           self.dataloader.dataset.get_sensor_modality(img_id),
                                           self.dataloader.dataset.get_sample_token(img_id) + '.txt')
            print('*****************************{:06d}*****************************'.format(img_id))
            
            ###Read Label#####
            # 1. Read Label
            # 2. Read the lines of label file, List the labels in the order of the objects written in the label file.
            label_folder = '/home/cv1/hdd/monodle/data/KITTI/object/training/label_2/'
            label_file = label_folder + '{:06d}.txt'.format(img_id)
            lf = open(label_file,'r')
            lines = lf.readlines()
            temp =[]
            for i in lines:
                temp.append(i.strip().split(' '))
            labels =[]


            ################# label format #################
            # 0: type
            # 1 : trucated
            # 2 : occluded
            # 3 : alpha
            # 4 : 2D left
            # 5 : 2D top
            # 6 : 2D right
            # 7 : 2D bottom
            # 8 : height
            # 9 : width
            # 10 : lenght
            # 11 : x
            # 12 : y
            # 13 : z
            # 14 : rotatio_y
            # 15 : score
            ####################################################
            print('*****************************GT Value*****************************')
            gt_car = {}
            g_cnt=0

            for i in temp:
                labels.append(i)
                if(i[0]=='Car'):
                    gt_car[g_cnt]=i
                    g_cnt+=1
            

            #check the gt_car (that save the gt values)
            #the gt_car is the dict(Key: idx of each objects Value: GT value of Kitti dataset)
            for i in range(g_cnt):
                print(gt_car[i])


            #dt_car list save the predicted value in regular order 
            
            dt_car = []
            for i in range(len(results[img_id])):
                temp=[]
                class_name = self.class_name[int(results[img_id][i][0])]
                temp.append(class_name)
                temp.append(0.0)
                temp.append(0)
                for j in range(1,len(results[img_id][i])):
                    temp.append(results[img_id][i][j])
                dt_car.append(temp)

            #Matching metric
            #Use the 3D location Distance 
            def distance(x1, y1, z1, x2, y2, z2):
                d = math.sqrt(math.pow(abs(x2 - x1), 2) +math.pow(abs(y2 - y1), 2) +math.pow(abs(z2 - z1), 2)* 1.0)
                return d


            num_gt = len(gt_car)
            num_dt = len(dt_car)
            #Sometimes, there are no predicted value or gt values, So only work when there exsit gt values and predicted values

            if(num_dt>0 and num_gt>0):
                #dt_to_gt matching {Key : predicted objects ,Values: the most appropriate GT }
                dt_to_gt_matching ={}

                #initialize dt_to_gt_matching
                for i in range(num_dt):
                    dt_to_gt_matching[i]=-1

                for i in range(num_dt):
                    #each predicted values
                    min_distance = 1e12
                    matching_num = -1
                    for j in range(num_gt):
                        #calculate the distance (about 3D location) for each gt
                        cur_d = distance(dt_car[i][11],dt_car[i][12],dt_car[i][13],float(gt_car[j][11]),float(gt_car[j][12]),float(gt_car[j][13]))
                        if(min_distance>cur_d):
                            #Update the minimum distance
                            min_distance=cur_d
                            matching_num=j
                    dt_to_gt_matching[i]=matching_num
                # print(dt_to_gt_matching)

                #replace the value with gt value 
                for i in range(num_dt):
                    for j in range(0,len(dt_car[i])-1):
                        dt_car[i][j]= gt_car[dt_to_gt_matching[i]][j]

            print('*****************************Refine Value*****************************')
            f = open(output_path,'w')
            for i in range(len(dt_car)):
                f.write('{} 0.0 0'.format(dt_car[i][0]))
                print('{} 0.0 0'.format(dt_car[i][0]),end=' ')
                for j in range(3,len(dt_car[i])):
                    f.write(' {:.2f}'.format(float(dt_car[i][j])))
                    # print(dt_car[i][j],end='')
                    print(' {:.2f}'.format(dt_car[i][j]),end='')
                f.write('\n')
                print()
            f.close()

            print('*****************************Predicted Save Value*****************************')
            # f = open(output_path, 'w')
            for i in range(len(results[img_id])):
                class_name = self.class_name[int(results[img_id][i][0])]
                # f.write('{} 0.0 0'.format(class_name))
                print('{} 0.0 0'.format(class_name),end=' ')
                for j in range(1, len(results[img_id][i])):
                    # f.write(' {:.2f}'.format(results[img_id][i][j]))
                    print(' {:.2f}'.format(results[img_id][i][j]),end=' ')
                # f.write('\n')
                print()
            # f.close()
            #input("Press the key to Next images")
'''
