### ISSUE TITLE
question about training results?

### ISSUE THREAD

**Issue by Senwang98** [xinzhuma/monodle#12]
Hi, @xinzhuma 
Thanks for your amazing work!
I trained your code and got the following results:
![image](https://user-images.githubusercontent.com/23122139/131286534-bc883853-7b08-48c6-952f-50727a682829.png)
Do you have any suggestions about unstable training results? I think you have made code reproducible in `set_random_seed`.

**Comment by xinzhuma** [comment]
The results seem okay,  what's the problem?

**Comment by Senwang98** [comment]
@xinzhuma 
Aha, no questions. I just think the training should be 0.5 higher than that report in paper, this result already reach to your recent GUPNet! So, you think about 0.5 performance unstable is common in mono 3D detection field (just curious)?
And I will then close issue. Thanks for your reply.

**Comment by xinzhuma** [comment]
Yes, it's common on the KITTI dataset, mainly because there are only 3700+ training images. In the large-scale datasets, such as nuScenes and Waymo Open, the performance is stable.
Besides, we update some codes, so the average performance in this repo should better than the original ones we reported.

**Comment by Senwang98** [comment]
Ok, thanks for your explanation and I will try it.

**Comment by DuZzzs** [comment]
@Senwang98  你好，请问你是如何调整配置文件的？我用单卡，batch_size=6, lr=0.000625，仅得到了3d   AP:16.0271, 13.1879, 11.3544。谢谢

**Comment by Senwang98** [comment]
@DuZzzs 
Hi, 我使用两张卡去训的，配置文件我没有修改，就是默认提供的代码，当时我是觉得怎么突然很高都sota了，所以才提出了这个问题的。
另外，请问你那边训练的时候有注意到代码不可复现性的问题吗？随机种子设置似乎有些小问题我这边看起来。

**Comment by DuZzzs** [comment]
@Senwang98 请问两张卡需要安装分布式的东西吗？我是单机多卡，尝试多卡失败了。我仅注意到了测试时同一模型输出有波动，随机种子未做修改调试。另外我将代码部分写法修改，在torch1.7下训练的。

**Comment by Senwang98** [comment]
@DuZzzs 我使用的是2张1080ti，也是单机多卡，作者的代码拿过来就可以多卡训，不知道你这个是什么情况。另外pt1.7我没有训练过，我是用的跟作者对齐的pt环境。pt1.7会一直报userwarning，就是uint8和bool的转化在pytorch后续版本需要手动指定。
我这边情况是：非30系显卡用默认环境就可以直接跑没啥问题，30系显卡的话必须要pytorch1.7，也是可以多卡训的，昨晚测了没啥问题，只是没跑结果。

**Comment by xinzhuma** [comment]
目前支持DP下的单机多卡，不支持DDP下的多机多卡

**Comment by DuZzzs** [comment]
@Senwang98 @xinzhuma 谢谢，我后边试下。我之前以为不能多卡，就改到torch1.7的DDP了，，，
