### ISSUE TITLE
dataset mean

### ISSUE THREAD

**Issue by alfinnurhalim** [xinzhuma/monodle#15]
Hi. first of all, thank you for your great work.
I tried to customize the dataset loader because I using a custom dataset.
how did you calculate mean, std and cls_mean_size? 
![image](https://user-images.githubusercontent.com/44990448/135123392-33eaa48d-d540-4669-a38f-0c2ea5ad2d77.png)

**Comment by xinzhuma** [comment]
@alfinnurhalim The mean and std are computed from the ImageNet, which is used for the pre-trained backbone in ImageNet, and you don't need to update them.
About the cls_mean_size, you need to collect the instances in your dataset and use the mean size of these instances to update the numbers.

**Comment by Senwang98** [comment]
@alfinnurhalim 
Just use label's height, width, depth to get cls_mean_size.
mean and std are calculated from ImageNet, you can regard it as super param (it is widely used in most cv tasks).

**Comment by alfinnurhalim** [comment]
I see. thanks for the explanation
