### ISSUE TITLE
About test dataset results

### ISSUE THREAD

**Issue by kdheejb7** [xinzhuma/monodle#16]
Hello,

I have read your paper, Delving into Localization Errors for Monocular 3D Object Detection! 

I think the paper is amazing, so I want to reproduce your model via this GitHub repository. 
However, I figured out there are no labels for the test dataset provided by KITTI.
How did you get the result for the test dataset of KITTI?
If you have any labels for the test set, could you please share me? 

Thank you!

**Comment by xinzhuma** [comment]
> Hello,
> 
> I have read your paper, Delving into Localization Errors for Monocular 3D Object Detection!
> 
> I think the paper is amazing, so I want to reproduce your model via this GitHub repository. However, I figured out there are no labels for the test dataset provided by KITTI. How did you get the result for the test dataset of KITTI? If you have any labels for the test set, could you please share me?
> 
> Thank you!

There is no test data annotation available, the only way is to submit the results to the KITTI test server: http://www.cvlibs.net/datasets/kitti/user_login.php

**Comment by kdheejb7** [comment]
Thanks for the very quick reply!
Your reply is enough to answer my question.

Thank you again, and I will close this issue :)
