### ISSUE TITLE
Object level training weight

### ISSUE THREAD

**Issue by alfinnurhalim** [xinzhuma/monodle#18]
Hi, thank you for your great work. I have several questions

From the paper, the module discards all samples over a certain distance using 2 scheme, at which parts of the code did you implement this? because I feel like our trained model struggling to detect both far and close objects. it only able to detect objects at a very specific distance. is it possible to train all samples instead? I can ensure the objects is visible enough to be trained because we did preprocessing before to discard potentially disturbing object.

This might be off the topic but, I wonder if you know how does Kitti calculates the projection matrix P0 from the calibration file?. we're about to use our own camera for real-scene inference, and I don't know how to get the projection matrix for inference, from its original paper, it calculated as 
![image](https://user-images.githubusercontent.com/44990448/138076188-6853beab-ff14-4bd4-b91c-343394765b24.png)
but our camera fu and fv is only like 2 mm but from the sample I took from the KITTI dataset, the fu and fv is like 718?
I just want to know if you might have an insight into this. I'll close the issue regardless of your answer

Thank you very much in advance

**Comment by xinzhuma** [comment]
hi, you can refer to https://github.com/xinzhuma/monodle/blob/e426aa65fdc7ceedcaab0d637acf3d3425d0736c/lib/datasets/kitti/kitti_dataset.py#L200 for the first question.
However, I don't know how the KITTI team calibrated the cameras.

**Comment by alfinnurhalim** [comment]
Thank you very much
