### ISSUE TITLE
How can I get the projected 3d bounding box?

### ISSUE THREAD

**Issue by kdheejb7** [xinzhuma/monodle#19]
Hello, 

I succeeded in inference with test data thanks for the kind documentations about how to do the test,
and I got the output that includes a class name and 15 float numbers for each detected object.
My output of inference
![image](https://user-images.githubusercontent.com/39160667/139096618-803177aa-2e53-4432-87af-2495cb3038b0.png)

I want to represent the projected 3D bounding box which is the result of object detection on the original image like you did.
![image](https://user-images.githubusercontent.com/39160667/139095322-94ff9ebb-1a40-4c46-b695-bb59d8612164.png)

I found 'draw_projected_box3d' function in lib/dataset/utils.py, but I don't think this is a function that can be used with my output. Because this function requires an array of [8,3] as input, but in my result there are only 15 numbers representing the 3d bbox.

```
def draw_projected_box3d(image, corners3d, color=(255, 255, 255), thickness=1):
    ''' Draw 3d bounding box in image
    input:
        image: RGB image
        corners3d: (8,3) array of vertices (in image plane) for the 3d box in following order:
            1 -------- 0
           /|         /|
          2 -------- 3 .
          | |        | |
          . 5 -------- 4
          |/         |/
          6 -------- 7
    '''

    corners3d = corners3d.astype(np.int32)
    for k in range(0, 4):
        i, j = k, (k + 1) % 4
        cv2.line(image, (corners3d[i, 0], corners3d[i, 1]), (corners3d[j, 0], corners3d[j, 1]), color, thickness, lineType=cv2.LINE_AA)
        i, j = k + 4, (k + 1) % 4 + 4
        cv2.line(image, (corners3d[i, 0], corners3d[i, 1]), (corners3d[j, 0], corners3d[j, 1]), color, thickness, lineType=cv2.LINE_AA)
        i, j = k, k + 4
        cv2.line(image, (corners3d[i, 0], corners3d[i, 1]), (corners3d[j, 0], corners3d[j, 1]), color, thickness, lineType=cv2.LINE_AA)
    return image
```

How can I get the image with the projected 3d bounding box with my output?

Thanks!

**Comment by xinzhuma** [comment]
you should use your results to compute the corners in 3D space first, and the related codes are also included. 
you can refer to this script: https://github.com/xinzhuma/patchnet/blob/master/tools/visualization.py

**Comment by kdheejb7** [comment]
Thanks for the quick response!

I took a look at the reference script.
The script describes how to 3d bbox from detection with lidar, but monoDLE is about monocular object detection. 
```
    def generate_corners3d(self):
        """
        generate corners3d representation for this object
        :return corners_3d: (8, 3) corners of box3d in camera coord
        """
        l, h, w = self.l, self.h, self.w
        x_corners = [l / 2, l / 2, -l / 2, -l / 2, l / 2, l / 2, -l / 2, -l / 2]
        y_corners = [0, 0, 0, 0, -h, -h, -h, -h]
        z_corners = [w / 2, -w / 2, -w / 2, w / 2, w / 2, -w / 2, -w / 2, w / 2]

        R = np.array([[np.cos(self.ry), 0, np.sin(self.ry)],
                      [0, 1, 0],
                      [-np.sin(self.ry), 0, np.cos(self.ry)]])
        corners3d = np.vstack([x_corners, y_corners, z_corners])  # (3, 8)
        corners3d = np.dot(R, corners3d).T
        corners3d = corners3d + self.pos
        return corners3d
```
The function seems to generate corners in 3D space as you said,
but I think this function cannot be used with my output (class name + 15 float numbers).

Could you please explain in more detail?

**Comment by kdheejb7** [comment]
After looking more closely at the reference code, I knew what to do.

Thanks a lot :)
