### ISSUE TITLE
[Evaluation Problem] .pth file doesn't have key about CenterNet3D

### ISSUE THREAD

**Issue by sjg02122** [xinzhuma/monodle#2]
Thank you for your great working.
I saw the closed issue#1 . 

So I work the code 

`python ../../tools/train_val.py --config kitti_example.yaml`

and after 140 epochs

I try to run the code:
`python ../../tools/train_val.py --config kitti_example.yaml --e`

and I faced the below problem.
How can I fix this problem? 

2021-06-17 17:08:50,661   INFO  ###################  Evaluation Only  ##################
2021-06-17 17:08:50,661   INFO  ==> Loading from checkpoint 'checkpoints/checkpoint_epoch_140.pth'
Traceback (most recent call last):
  File "../../tools/train_val.py", line 85, in <module>
    main()
  File "../../tools/train_val.py", line 53, in main
    tester.test()
  File "/HDD/monodle/lib/helpers/tester_helper.py", line 36, in test
    logger=self.logger)
  File "/HDD/monodle/lib/helpers/save_helper.py", line 37, in load_checkpoint
    model.load_state_dict(checkpoint['model_state'])
  File "/home/cv1/miniconda3/envs/monodle/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CenterNet3D:
        Missing key(s) in state_dict: "backbone.base_layer.0.weight", "backbone.base_layer.1.weight", "backbone.base_layer.1.bias", "backbone.base_layer.1.running_mean", "backbone.base_layer.1.running_var", "backbone.level0.0.weight", "backbone.level0.1.weight", "backbone.level0.1.bias", "backbone.level0.1.running_mean", "backbone.level0.1.running_var", "backbone.level1.0.weight", "backbone.level1.1.weight", "backbone.level1.1.bias", "backbone.level1.1.running_mean", "backbone.level1.1.running_var", "backbone.level2.tree1.conv1.weight", "backbone.level2.tree1.bn1.weight", "backbone.level2.tree1.bn1.bias", "backbone.level2.tree1.bn1.running_mean", "backbone.level2.tree1.bn1.running_var", "backbone.level2.tree1.conv2.weight", "backbone.level2.tree1.bn2.weight", "backbone.level2.tree1.bn2.bias", "backbone.level2.tree1.bn2.running_mean", "backbone.level2.tree1.bn2.running_var", "backbone.level2.tree2.conv1.weight", "backbone.level2.tree2.bn1.weight", "backbone.level2.tree2.bn1.bias", "backbone.level2.tree2.bn1.running_mean", "backbone.level2.tree2.bn1.running_var", "backbone.level2.tree2.conv2.weight", "backbone.level2.tree2.bn2.weight", "backbone.level2.tree2.bn2.bias", "backbone.level2.tree2.bn2.running_mean", "backbone.level2.tree2.bn2.running_var", "backbone.level2.root.conv.weight", "backbone.level2.root.bn.weight", "backbone.level2.root.bn.bias", "backbone.level2.root.bn.running_mean", "backbone.level2.root.bn.running_var", "backbone.level2.project.0.weight", "backbone.level2.project.1.weight", "backbone.level2.project.1.bias", "backbone.level2.project.1.running_mean", "backbone.level2.project.1.running_var", "backbone.level3.tree1.tree1.conv1.weight", "backbone.level3.tree1.tree1.bn1.weight", "backbone.level3.tree1.tree1.bn1.bias", "backbone.level3.tree1.tree1.bn1.running_mean", "backbone.level3.tree1.tree1.bn1.running_var", "backbone.level3.tree1.tree1.conv2.weight", "backbone.level3.tree1.tree1.bn2.weight", "backbone.level3.tree1.tree1.bn2.bias", "backbone.level3.tree1.tree1.bn2.running_mean", "backbone.level3.tree1.tree1.bn2.running_var", "backbone.level3.tree1.tree2.conv1.weight", "backbone.level3.tree1.tree2.bn1.weight", "backbone.level3.tree1.tree2.bn1.bias", "backbone.level3.tree1.tree2.bn1.running_mean", "backbone.level3.tree1.tree2.bn1.running_var", "backbone.level3.tree1.tree2.conv2.weight", "backbone.level3.tree1.tree2.bn2.weight", "backbone.level3.tree1.tree2.bn2.bias", "backbone.level3.tree1.tree2.bn2.running_mean", "backbone.level3.tree1.tree2.bn2.running_var", "backbone.level3.tree1.root.conv.weight", "backbone.level3.tree1.root.bn.weight", "backbone.level3.tree1.root.bn.bias", "backbone.level3.tree1.root.bn.running_mean", "backbone.level3.tree1.root.bn.running_var", "backbone.level3.tree1.project.0.weight", "backbone.level3.tree1.project.1.weight", "backbone.level3.tree1.project.1.bias", "backbone.level3.tree1.project.1.running_mean", "backbone.level3.tree1.project.1.running_var", "backbone.level3.tree2.tree1.conv1.weight", "backbone.level3.tree2.tree1.bn1.weight", "backbone.level3.tree2.tree1.bn1.bias", "backbone.level3.tree2.tree1.bn1.running_mean", "backbone.level3.tree2.tree1.bn1.running_var", "backbone.level3.tree2.tree1.conv2.weight", "backbone.level3.tree2.tree1.bn2.weight", "backbone.level3.tree2.tree1.bn2.bias", "backbone.level3.tree2.tree1.bn2.running_mean", "backbone.level3.tree2.tree1.bn2.running_var", "backbone.level3.tree2.tree2.conv1.weight", "backbone.level3.tree2.tree2.bn1.weight", "backbone.level3.tree2.tree2.bn1.bias", "backbone.level3.tree2.tree2.bn1.running_mean", "backbone.level3.tree2.tree2.bn1.running_var", "backbone.level3.tree2.tree2.conv2.weight", "backbone.level3.tree2.tree2.bn2.weight", "backbone.level3.tree2.tree2.bn2.bias", "backbone.level3.tree2.tree2.bn2.running_mean", "backbone.level3.tree2.tree2.bn2.running_var", "backbone.level3.tree2.root.conv.weight", "backbone.level3.tree2.root.bn.weight", "backbone.level3.tree2.root.bn.bias", "backbone.level3.tree2.root.bn.running_mean", "backbone.level3.tree2.root.bn.running_var", "backbone.level3.project.0.weight", "backbone.level3.project.1.weight", "backbone.level3.project.1.bias", "backbone.level3.project.1.running_mean", "backbone.level3.project.1.running_var", "backbone.level4.tree1.tree1.conv1.weight", "backbone.level4.tree1.tree1.bn1.weight", "backbone.level4.tree1.tree1.bn1.bias", "backbone.level4.tree1.tree1.bn1.running_mean", "backbone.level4.tree1.tree1.bn1.running_var", "backbone.level4.tree1.tree1.conv2.weight", "backbone.level4.tree1.tree1.bn2.weight", "backbone.level4.tree1.tree1.bn2.bias", "backbone.level4.tree1.tree1.bn2.running_mean", "backbone.level4.tree1.tree1.bn2.running_var", "backbone.level4.tree1.tree2.conv1.weight", "backbone.level4.tree1.tree2.bn1.weight", "backbone.level4.tree1.tree2.bn1.bias", "backbone.level4.tree1.tree2.bn1.running_mean", "backbone.level4.tree1.tree2.bn1.running_var", "backbone.level4.tree1.tree2.conv2.weight", "backbone.level4.tree1.tree2.bn2.weight", "backbone.level4.tree1.tree2.bn2.bias", "backbone.level4.tree1.tree2.bn2.running_mean", "backbone.level4.tree1.tree2.bn2.running_var", "backbone.level4.tree1.root.conv.weight", "backbone.level4.tree1.root.bn.weight", "backbone.level4.tree1.root.bn.bias", "backbone.level4.tree1.root.bn.running_mean", "backbone.level4.tree1.root.bn.running_var", "backbone.level4.tree1.project.0.weight", "backbone.level4.tree1.project.1.weight", "backbone.level4.tree1.project.1.bias", "backbone.level4.tree1.project.1.running_mean", "backbone.level4.tree1.project.1.running_var", "backbone.level4.tree2.tree1.conv1.weight", "backbone.level4.tree2.tree1.bn1.weight", "backbone.level4.tree2.tree1.bn1.bias", "backbone.level4.tree2.tree1.bn1.running_mean", "backbone.level4.tree2.tree1.bn1.running_var", "backbone.level4.tree2.tree1.conv2.weight", "backbone.level4.tree2.tree1.bn2.weight", "backbone.level4.tree2.tree1.bn2.bias", "backbone.level4.tree2.tree1.bn2.running_mean", "backbone.level4.tree2.tree1.bn2.running_var", "backbone.level4.tree2.tree2.conv1.weight", "backbone.level4.tree2.tree2.bn1.weight", "backbone.level4.tree2.tree2.bn1.bias", "backbone.level4.tree2.tree2.bn1.running_mean", "backbone.level4.tree2.tree2.bn1.running_var", "backbone.level4.tree2.tree2.conv2.weight", "backbone.level4.tree2.tree2.bn2.weight", "backbone.level4.tree2.tree2.bn2.bias", "backbone.level4.tree2.tree2.bn2.running_mean", "backbone.level4.tree2.tree2.bn2.running_var", "backbone.level4.tree2.root.conv.weight", "backbone.level4.tree2.root.bn.weight", "backbone.level4.tree2.root.bn.bias", "backbone.level4.tree2.root.bn.running_mean", "backbone.level4.tree2.root.bn.running_var", "backbone.level4.project.0.weight", "backbone.level4.project.1.weight", "backbone.level4.project.1.bias", "backbone.level4.project.1.running_mean", "backbone.level4.project.1.running_var", "backbone.level5.tree1.conv1.weight", "backbone.level5.tree1.bn1.weight", "backbone.level5.tree1.bn1.bias", "backbone.level5.tree1.bn1.running_mean", "backbone.level5.tree1.bn1.running_var", "backbone.level5.tree1.conv2.weight", "backbone.level5.tree1.bn2.weight", "backbone.level5.tree1.bn2.bias", "backbone.level5.tree1.bn2.running_mean", "backbone.level5.tree1.bn2.running_var", "backbone.level5.tree2.conv1.weight", "backbone.level5.tree2.bn1.weight", "backbone.level5.tree2.bn1.bias", "backbone.level5.tree2.bn1.running_mean", "backbone.level5.tree2.bn1.running_var", "backbone.level5.tree2.conv2.weight", "backbone.level5.tree2.bn2.weight", "backbone.level5.tree2.bn2.bias", "backbone.level5.tree2.bn2.running_mean", "backbone.level5.tree2.bn2.running_var", "backbone.level5.root.conv.weight", "backbone.level5.root.bn.weight", "backbone.level5.root.bn.bias", "backbone.level5.root.bn.running_mean", "backbone.level5.root.bn.running_var", "backbone.level5.project.0.weight", "backbone.level5.project.1.weight", "backbone.level5.project.1.bias", "backbone.level5.project.1.running_mean", "backbone.level5.project.1.running_var", "backbone.fc.weight", "backbone.fc.bias", "neck.ida_0.proj_1.conv.weight", "neck.ida_0.proj_1.bn.weight", "neck.ida_0.proj_1.bn.bias", "neck.ida_0.proj_1.bn.running_mean", "neck.ida_0.proj_1.bn.running_var", "neck.ida_0.up_1.weight", "neck.ida_0.node_1.conv.weight", "neck.ida_0.node_1.bn.weight", "neck.ida_0.node_1.bn.bias", "neck.ida_0.node_1.bn.running_mean", "neck.ida_0.node_1.bn.running_var", "neck.ida_1.proj_1.conv.weight", "neck.ida_1.proj_1.bn.weight", "neck.ida_1.proj_1.bn.bias", "neck.ida_1.proj_1.bn.running_mean", "neck.ida_1.proj_1.bn.running_var", "neck.ida_1.up_1.weight", "neck.ida_1.node_1.conv.weight", "neck.ida_1.node_1.bn.weight", "neck.ida_1.node_1.bn.bias", "neck.ida_1.node_1.bn.running_mean", "neck.ida_1.node_1.bn.running_var", "neck.ida_1.proj_2.conv.weight", "neck.ida_1.proj_2.bn.weight", "neck.ida_1.proj_2.bn.bias", "neck.ida_1.proj_2.bn.running_mean", "neck.ida_1.proj_2.bn.running_var", "neck.ida_1.up_2.weight", "neck.ida_1.node_2.conv.weight", "neck.ida_1.node_2.bn.weight", "neck.ida_1.node_2.bn.bias", "neck.ida_1.node_2.bn.running_mean", "neck.ida_1.node_2.bn.running_var", "neck.ida_2.proj_1.conv.weight", "neck.ida_2.proj_1.bn.weight", "neck.ida_2.proj_1.bn.bias", "neck.ida_2.proj_1.bn.running_mean", "neck.ida_2.proj_1.bn.running_var", "neck.ida_2.up_1.weight", "neck.ida_2.node_1.conv.weight", "neck.ida_2.node_1.bn.weight", "neck.ida_2.node_1.bn.bias", "neck.ida_2.node_1.bn.running_mean", "neck.ida_2.node_1.bn.running_var", "neck.ida_2.proj_2.conv.weight", "neck.ida_2.proj_2.bn.weight", "neck.ida_2.proj_2.bn.bias", "neck.ida_2.proj_2.bn.running_mean", "neck.ida_2.proj_2.bn.running_var", "neck.ida_2.up_2.weight", "neck.ida_2.node_2.conv.weight", "neck.ida_2.node_2.bn.weight", "neck.ida_2.node_2.bn.bias", "neck.ida_2.node_2.bn.running_mean", "neck.ida_2.node_2.bn.running_var", "neck.ida_2.proj_3.conv.weight", "neck.ida_2.proj_3.bn.weight", "neck.ida_2.proj_3.bn.bias", "neck.ida_2.proj_3.bn.running_mean", "neck.ida_2.proj_3.bn.running_var", "neck.ida_2.up_3.weight", "neck.ida_2.node_3.conv.weight", "neck.ida_2.node_3.bn.weight", "neck.ida_2.node_3.bn.bias", "neck.ida_2.node_3.bn.running_mean", "neck.ida_2.node_3.bn.running_var", "heatmap.0.weight", "heatmap.0.bias", "heatmap.2.weight", "heatmap.2.bias", "offset_2d.0.weight", "offset_2d.0.bias", "offset_2d.2.weight", "offset_2d.2.bias", "size_2d.0.weight", "size_2d.0.bias", "size_2d.2.weight", "size_2d.2.bias", "depth.0.weight", "depth.0.bias", "depth.2.weight", "depth.2.bias", "offset_3d.0.weight", "offset_3d.0.bias", "offset_3d.2.weight", "offset_3d.2.bias", "size_3d.0.weight", "size_3d.0.bias", "size_3d.2.weight", "size_3d.2.bias", "heading.0.weight", "heading.0.bias", "heading.2.weight", "heading.2.bias". 
        Unexpected key(s) in state_dict: "module.backbone.base_layer.0.weight", "module.backbone.base_layer.1.weight", "module.backbone.base_layer.1.bias", "module.backbone.base_layer.1.running_mean", "module.backbone.base_layer.1.running_var", "module.backbone.base_layer.1.num_batches_tracked", "module.backbone.level0.0.weight", "module.backbone.level0.1.weight", "module.backbone.level0.1.bias", "module.backbone.level0.1.running_mean", "module.backbone.level0.1.running_var", "module.backbone.level0.1.num_batches_tracked", "module.backbone.level1.0.weight", "module.backbone.level1.1.weight", "module.backbone.level1.1.bias", "module.backbone.level1.1.running_mean", "module.backbone.level1.1.running_var", "module.backbone.level1.1.num_batches_tracked", "module.backbone.level2.tree1.conv1.weight", "module.backbone.level2.tree1.bn1.weight", "module.backbone.level2.tree1.bn1.bias", "module.backbone.level2.tree1.bn1.running_mean", "module.backbone.level2.tree1.bn1.running_var", "module.backbone.level2.tree1.bn1.num_batches_tracked", "module.backbone.level2.tree1.conv2.weight", "module.backbone.level2.tree1.bn2.weight", "module.backbone.level2.tree1.bn2.bias", "module.backbone.level2.tree1.bn2.running_mean", "module.backbone.level2.tree1.bn2.running_var", "module.backbone.level2.tree1.bn2.num_batches_tracked", "module.backbone.level2.tree2.conv1.weight", "module.backbone.level2.tree2.bn1.weight", "module.backbone.level2.tree2.bn1.bias", "module.backbone.level2.tree2.bn1.running_mean", "module.backbone.level2.tree2.bn1.running_var", "module.backbone.level2.tree2.bn1.num_batches_tracked", "module.backbone.level2.tree2.conv2.weight", "module.backbone.level2.tree2.bn2.weight", "module.backbone.level2.tree2.bn2.bias", "module.backbone.level2.tree2.bn2.running_mean", "module.backbone.level2.tree2.bn2.running_var", "module.backbone.level2.tree2.bn2.num_batches_tracked", "module.backbone.level2.root.conv.weight", "module.backbone.level2.root.bn.weight", "module.backbone.level2.root.bn.bias", "module.backbone.level2.root.bn.running_mean", "module.backbone.level2.root.bn.running_var", "module.backbone.level2.root.bn.num_batches_tracked", "module.backbone.level2.project.0.weight", "module.backbone.level2.project.1.weight", "module.backbone.level2.project.1.bias", "module.backbone.level2.project.1.running_mean", "module.backbone.level2.project.1.running_var", "module.backbone.level2.project.1.num_batches_tracked", "module.backbone.level3.tree1.tree1.conv1.weight", "module.backbone.level3.tree1.tree1.bn1.weight", "module.backbone.level3.tree1.tree1.bn1.bias", "module.backbone.level3.tree1.tree1.bn1.running_mean", "module.backbone.level3.tree1.tree1.bn1.running_var", "module.backbone.level3.tree1.tree1.bn1.num_batches_tracked", "module.backbone.level3.tree1.tree1.conv2.weight", "module.backbone.level3.tree1.tree1.bn2.weight", "module.backbone.level3.tree1.tree1.bn2.bias", "module.backbone.level3.tree1.tree1.bn2.running_mean", "module.backbone.level3.tree1.tree1.bn2.running_var", "module.backbone.level3.tree1.tree1.bn2.num_batches_tracked", "module.backbone.level3.tree1.tree2.conv1.weight", "module.backbone.level3.tree1.tree2.bn1.weight", "module.backbone.level3.tree1.tree2.bn1.bias", "module.backbone.level3.tree1.tree2.bn1.running_mean", "module.backbone.level3.tree1.tree2.bn1.running_var", "module.backbone.level3.tree1.tree2.bn1.num_batches_tracked", "module.backbone.level3.tree1.tree2.conv2.weight", "module.backbone.level3.tree1.tree2.bn2.weight", "module.backbone.level3.tree1.tree2.bn2.bias", "module.backbone.level3.tree1.tree2.bn2.running_mean", "module.backbone.level3.tree1.tree2.bn2.running_var", "module.backbone.level3.tree1.tree2.bn2.num_batches_tracked", "module.backbone.level3.tree1.root.conv.weight", "module.backbone.level3.tree1.root.bn.weight", "module.backbone.level3.tree1.root.bn.bias", "module.backbone.level3.tree1.root.bn.running_mean", "module.backbone.level3.tree1.root.bn.running_var", "module.backbone.level3.tree1.root.bn.num_batches_tracked", "module.backbone.level3.tree1.project.0.weight", "module.backbone.level3.tree1.project.1.weight", "module.backbone.level3.tree1.project.1.bias", "module.backbone.level3.tree1.project.1.running_mean", "module.backbone.level3.tree1.project.1.running_var", "module.backbone.level3.tree1.project.1.num_batches_tracked", "module.backbone.level3.tree2.tree1.conv1.weight", "module.backbone.level3.tree2.tree1.bn1.weight", "module.backbone.level3.tree2.tree1.bn1.bias", "module.backbone.level3.tree2.tree1.bn1.running_mean", "module.backbone.level3.tree2.tree1.bn1.running_var", "module.backbone.level3.tree2.tree1.bn1.num_batches_tracked", "module.backbone.level3.tree2.tree1.conv2.weight", "module.backbone.level3.tree2.tree1.bn2.weight", "module.backbone.level3.tree2.tree1.bn2.bias", "module.backbone.level3.tree2.tree1.bn2.running_mean", "module.backbone.level3.tree2.tree1.bn2.running_var", "module.backbone.level3.tree2.tree1.bn2.num_batches_tracked", "module.backbone.level3.tree2.tree2.conv1.weight", "module.backbone.level3.tree2.tree2.bn1.weight", "module.backbone.level3.tree2.tree2.bn1.bias", "module.backbone.level3.tree2.tree2.bn1.running_mean", "module.backbone.level3.tree2.tree2.bn1.running_var", "module.backbone.level3.tree2.tree2.bn1.num_batches_tracked", "module.backbone.level3.tree2.tree2.conv2.weight", "module.backbone.level3.tree2.tree2.bn2.weight", "module.backbone.level3.tree2.tree2.bn2.bias", "module.backbone.level3.tree2.tree2.bn2.running_mean", "module.backbone.level3.tree2.tree2.bn2.running_var", "module.backbone.level3.tree2.tree2.bn2.num_batches_tracked", "module.backbone.level3.tree2.root.conv.weight", "module.backbone.level3.tree2.root.bn.weight", "module.backbone.level3.tree2.root.bn.bias", "module.backbone.level3.tree2.root.bn.running_mean", "module.backbone.level3.tree2.root.bn.running_var", "module.backbone.level3.tree2.root.bn.num_batches_tracked", "module.backbone.level3.project.0.weight", "module.backbone.level3.project.1.weight", "module.backbone.level3.project.1.bias", "module.backbone.level3.project.1.running_mean", "module.backbone.level3.project.1.running_var", "module.backbone.level3.project.1.num_batches_tracked", "module.backbone.level4.tree1.tree1.conv1.weight", "module.backbone.level4.tree1.tree1.bn1.weight", "module.backbone.level4.tree1.tree1.bn1.bias", "module.backbone.level4.tree1.tree1.bn1.running_mean", "module.backbone.level4.tree1.tree1.bn1.running_var", "module.backbone.level4.tree1.tree1.bn1.num_batches_tracked", "module.backbone.level4.tree1.tree1.conv2.weight", "module.backbone.level4.tree1.tree1.bn2.weight", "module.backbone.level4.tree1.tree1.bn2.bias", "module.backbone.level4.tree1.tree1.bn2.running_mean", "module.backbone.level4.tree1.tree1.bn2.running_var", "module.backbone.level4.tree1.tree1.bn2.num_batches_tracked", "module.backbone.level4.tree1.tree2.conv1.weight", "module.backbone.level4.tree1.tree2.bn1.weight", "module.backbone.level4.tree1.tree2.bn1.bias", "module.backbone.level4.tree1.tree2.bn1.running_mean", "module.backbone.level4.tree1.tree2.bn1.running_var", "module.backbone.level4.tree1.tree2.bn1.num_batches_tracked", "module.backbone.level4.tree1.tree2.conv2.weight", "module.backbone.level4.tree1.tree2.bn2.weight", "module.backbone.level4.tree1.tree2.bn2.bias", "module.backbone.level4.tree1.tree2.bn2.running_mean", "module.backbone.level4.tree1.tree2.bn2.running_var", "module.backbone.level4.tree1.tree2.bn2.num_batches_tracked", "module.backbone.level4.tree1.root.conv.weight", "module.backbone.level4.tree1.root.bn.weight", "module.backbone.level4.tree1.root.bn.bias", "module.backbone.level4.tree1.root.bn.running_mean", "module.backbone.level4.tree1.root.bn.running_var", "module.backbone.level4.tree1.root.bn.num_batches_tracked", "module.backbone.level4.tree1.project.0.weight", "module.backbone.level4.tree1.project.1.weight", "module.backbone.level4.tree1.project.1.bias", "module.backbone.level4.tree1.project.1.running_mean", "module.backbone.level4.tree1.project.1.running_var", "module.backbone.level4.tree1.project.1.num_batches_tracked", "module.backbone.level4.tree2.tree1.conv1.weight", "module.backbone.level4.tree2.tree1.bn1.weight", "module.backbone.level4.tree2.tree1.bn1.bias", "module.backbone.level4.tree2.tree1.bn1.running_mean", "module.backbone.level4.tree2.tree1.bn1.running_var", "module.backbone.level4.tree2.tree1.bn1.num_batches_tracked", "module.backbone.level4.tree2.tree1.conv2.weight", "module.backbone.level4.tree2.tree1.bn2.weight", "module.backbone.level4.tree2.tree1.bn2.bias", "module.backbone.level4.tree2.tree1.bn2.running_mean", "module.backbone.level4.tree2.tree1.bn2.running_var", "module.backbone.level4.tree2.tree1.bn2.num_batches_tracked", "module.backbone.level4.tree2.tree2.conv1.weight", "module.backbone.level4.tree2.tree2.bn1.weight", "module.backbone.level4.tree2.tree2.bn1.bias", "module.backbone.level4.tree2.tree2.bn1.running_mean", "module.backbone.level4.tree2.tree2.bn1.running_var", "module.backbone.level4.tree2.tree2.bn1.num_batches_tracked", "module.backbone.level4.tree2.tree2.conv2.weight", "module.backbone.level4.tree2.tree2.bn2.weight", "module.backbone.level4.tree2.tree2.bn2.bias", "module.backbone.level4.tree2.tree2.bn2.running_mean", "module.backbone.level4.tree2.tree2.bn2.running_var", "module.backbone.level4.tree2.tree2.bn2.num_batches_tracked", "module.backbone.level4.tree2.root.conv.weight", "module.backbone.level4.tree2.root.bn.weight", "module.backbone.level4.tree2.root.bn.bias", "module.backbone.level4.tree2.root.bn.running_mean", "module.backbone.level4.tree2.root.bn.running_var", "module.backbone.level4.tree2.root.bn.num_batches_tracked", "module.backbone.level4.project.0.weight", "module.backbone.level4.project.1.weight", "module.backbone.level4.project.1.bias", "module.backbone.level4.project.1.running_mean", "module.backbone.level4.project.1.running_var", "module.backbone.level4.project.1.num_batches_tracked", "module.backbone.level5.tree1.conv1.weight", "module.backbone.level5.tree1.bn1.weight", "module.backbone.level5.tree1.bn1.bias", "module.backbone.level5.tree1.bn1.running_mean", "module.backbone.level5.tree1.bn1.running_var", "module.backbone.level5.tree1.bn1.num_batches_tracked", "module.backbone.level5.tree1.conv2.weight", "module.backbone.level5.tree1.bn2.weight", "module.backbone.level5.tree1.bn2.bias", "module.backbone.level5.tree1.bn2.running_mean", "module.backbone.level5.tree1.bn2.running_var", "module.backbone.level5.tree1.bn2.num_batches_tracked", "module.backbone.level5.tree2.conv1.weight", "module.backbone.level5.tree2.bn1.weight", "module.backbone.level5.tree2.bn1.bias", "module.backbone.level5.tree2.bn1.running_mean", "module.backbone.level5.tree2.bn1.running_var", "module.backbone.level5.tree2.bn1.num_batches_tracked", "module.backbone.level5.tree2.conv2.weight", "module.backbone.level5.tree2.bn2.weight", "module.backbone.level5.tree2.bn2.bias", "module.backbone.level5.tree2.bn2.running_mean", "module.backbone.level5.tree2.bn2.running_var", "module.backbone.level5.tree2.bn2.num_batches_tracked", "module.backbone.level5.root.conv.weight", "module.backbone.level5.root.bn.weight", "module.backbone.level5.root.bn.bias", "module.backbone.level5.root.bn.running_mean", "module.backbone.level5.root.bn.running_var", "module.backbone.level5.root.bn.num_batches_tracked", "module.backbone.level5.project.0.weight", "module.backbone.level5.project.1.weight", "module.backbone.level5.project.1.bias", "module.backbone.level5.project.1.running_mean", "module.backbone.level5.project.1.running_var", "module.backbone.level5.project.1.num_batches_tracked", "module.backbone.fc.weight", "module.backbone.fc.bias", "module.neck.ida_0.proj_1.conv.weight", "module.neck.ida_0.proj_1.bn.weight", "module.neck.ida_0.proj_1.bn.bias", "module.neck.ida_0.proj_1.bn.running_mean", "module.neck.ida_0.proj_1.bn.running_var", "module.neck.ida_0.proj_1.bn.num_batches_tracked", "module.neck.ida_0.up_1.weight", "module.neck.ida_0.node_1.conv.weight", "module.neck.ida_0.node_1.bn.weight", "module.neck.ida_0.node_1.bn.bias", "module.neck.ida_0.node_1.bn.running_mean", "module.neck.ida_0.node_1.bn.running_var", "module.neck.ida_0.node_1.bn.num_batches_tracked", "module.neck.ida_1.proj_1.conv.weight", "module.neck.ida_1.proj_1.bn.weight", "module.neck.ida_1.proj_1.bn.bias", "module.neck.ida_1.proj_1.bn.running_mean", "module.neck.ida_1.proj_1.bn.running_var", "module.neck.ida_1.proj_1.bn.num_batches_tracked", "module.neck.ida_1.up_1.weight", "module.neck.ida_1.node_1.conv.weight", "module.neck.ida_1.node_1.bn.weight", "module.neck.ida_1.node_1.bn.bias", "module.neck.ida_1.node_1.bn.running_mean", "module.neck.ida_1.node_1.bn.running_var", "module.neck.ida_1.node_1.bn.num_batches_tracked", "module.neck.ida_1.proj_2.conv.weight", "module.neck.ida_1.proj_2.bn.weight", "module.neck.ida_1.proj_2.bn.bias", "module.neck.ida_1.proj_2.bn.running_mean", "module.neck.ida_1.proj_2.bn.running_var", "module.neck.ida_1.proj_2.bn.num_batches_tracked", "module.neck.ida_1.up_2.weight", "module.neck.ida_1.node_2.conv.weight", "module.neck.ida_1.node_2.bn.weight", "module.neck.ida_1.node_2.bn.bias", "module.neck.ida_1.node_2.bn.running_mean", "module.neck.ida_1.node_2.bn.running_var", "module.neck.ida_1.node_2.bn.num_batches_tracked", "module.neck.ida_2.proj_1.conv.weight", "module.neck.ida_2.proj_1.bn.weight", "module.neck.ida_2.proj_1.bn.bias", "module.neck.ida_2.proj_1.bn.running_mean", "module.neck.ida_2.proj_1.bn.running_var", "module.neck.ida_2.proj_1.bn.num_batches_tracked", "module.neck.ida_2.up_1.weight", "module.neck.ida_2.node_1.conv.weight", "module.neck.ida_2.node_1.bn.weight", "module.neck.ida_2.node_1.bn.bias", "module.neck.ida_2.node_1.bn.running_mean", "module.neck.ida_2.node_1.bn.running_var", "module.neck.ida_2.node_1.bn.num_batches_tracked", "module.neck.ida_2.proj_2.conv.weight", "module.neck.ida_2.proj_2.bn.weight", "module.neck.ida_2.proj_2.bn.bias", "module.neck.ida_2.proj_2.bn.running_mean", "module.neck.ida_2.proj_2.bn.running_var", "module.neck.ida_2.proj_2.bn.num_batches_tracked", "module.neck.ida_2.up_2.weight", "module.neck.ida_2.node_2.conv.weight", "module.neck.ida_2.node_2.bn.weight", "module.neck.ida_2.node_2.bn.bias", "module.neck.ida_2.node_2.bn.running_mean", "module.neck.ida_2.node_2.bn.running_var", "module.neck.ida_2.node_2.bn.num_batches_tracked", "module.neck.ida_2.proj_3.conv.weight", "module.neck.ida_2.proj_3.bn.weight", "module.neck.ida_2.proj_3.bn.bias", "module.neck.ida_2.proj_3.bn.running_mean", "module.neck.ida_2.proj_3.bn.running_var", "module.neck.ida_2.proj_3.bn.num_batches_tracked", "module.neck.ida_2.up_3.weight", "module.neck.ida_2.node_3.conv.weight", "module.neck.ida_2.node_3.bn.weight", "module.neck.ida_2.node_3.bn.bias", "module.neck.ida_2.node_3.bn.running_mean", "module.neck.ida_2.node_3.bn.running_var", "module.neck.ida_2.node_3.bn.num_batches_tracked", "module.heatmap.0.weight", "module.heatmap.0.bias", "module.heatmap.2.weight", "module.heatmap.2.bias", "module.offset_2d.0.weight", "module.offset_2d.0.bias", "module.offset_2d.2.weight", "module.offset_2d.2.bias", "module.size_2d.0.weight", "module.size_2d.0.bias", "module.size_2d.2.weight", "module.size_2d.2.bias", "module.depth.0.weight", "module.depth.0.bias", "module.depth.2.weight", "module.depth.2.bias", "module.offset_3d.0.weight", "module.offset_3d.0.bias", "module.offset_3d.2.weight", "module.offset_3d.2.bias", "module.size_3d.0.weight", "module.size_3d.0.bias", "module.size_3d.2.weight", "module.size_3d.2.bias", "module.heading.0.weight", "module.heading.0.bias", "module.heading.2.weight", "module.heading.2.bias".

**Comment by xinzhuma** [comment]
这个是因为我们提供的模型是分布式训练的，这里提供的是单机测试的代码。可以先参考一下 #1 中提供的方法。稍后我们会提供一个单机测试的checkpoint

**Comment by sjg02122** [comment]
Do you mean that the current checkpoints (.pth) file trained with multi-gpu cannot be evaluated?

Is it possible to evaluate with only .pth trained through single-gpu?

**Comment by xinzhuma** [comment]
In fact, this is a small bug in the checkpoint saving part. The code is fixed now, and the new models trained by yourself will be fine for evaluation. And I will upload a new checkpoint for quick evaluation. It may take one or two days because I need to re-train a model. If you want to evaluate the provide model right now, you can try the mentioned method in #1.

**Comment by sjg02122** [comment]
Oh Thank your kind.
I will try again. 

Thanks !
