### ISSUE TITLE
change backbone to DLA102, performance degradation

### ISSUE THREAD

**Issue by Senwang98** [xinzhuma/monodle#21]
Hi, @xinzhuma 
Have you test backbone such as DLA102?
When change config file `dla34` to `dla102`, the 3D AP is only 10 which is 6% performance degradation compared to default config setting.
Wishing for your reply.

**Comment by xinzhuma** [comment]
there are some bugs in the implementation of larger backbones

**Comment by Senwang98** [comment]
Hi, @xinzhuma 
Congratulation for monodistill is accepted by ICLR22. 
Two months ago, I also wanted to do some work on KD-det for mono 3d task, but I used monodle and monoflex repo to train **one teacher model**(such as better backbone and etc.) and **fail to see any performance improvement**.
Now, I want to know if monodistill work is based on monodle repo like GUPNet?
Also, I want to know if you have tried to use teacher which is trained on RGB images rather than lidar? how about your performance.

(I just want to know if this way work, which trains the teacher model based on mono image rather than Lidar, because I fail to see any improvement.)
Wishing for your reply!

**Comment by xinzhuma** [comment]
hi @Senwang98 
Thanks for your attention. This work is based on MonoDLE and GUPNet, and the code will be released for reproducibility. We scheduled it in March due to the Spring Festival and the ECCV DDL. We also trained the teacher net using the pre-trained depth maps, which is also working.  Please refer to Section 4.3 and Appendix A5 in https://arxiv.org/pdf/2201.10830.pdf for more details.

**Comment by Senwang98** [comment]
@xinzhuma 
Okay, thank you for replying. I will refer to monodistill for more details.
BTW, do you have any suggestions about this issue?(doge). Larger backbones didn't work for mono 3d task which is confusing.

**Comment by xinzhuma** [comment]
@Senwang98 It seems that there are some bugs in the implementation of larger DLA backbones, and I haven't checked the relevant code carefully, sorry for that. Someone has told me that they substituted the DLA with ResNet, and larger backbones did work at that setting. Hope this information is helpful.

**Comment by Senwang98** [comment]
@xinzhuma 
Got it!
I will try it and thanks again for your time. I will close this issue later.
