### ISSUE TITLE
numba.cuda.cudadrv.error

### ISSUE THREAD

**Issue by Dejavusd** [xinzhuma/monodle#23]
运行报错：
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
Could not find module 'nvvm.dll' (or one of its dependencies). Try using the full path with constructor syntax.

本地环境：torch 1.7.1 cuda 11.0 torchvision 0.8.2

**Comment by xinzhuma** [comment]
it seems there is something wrong with the environment, try to install or fix the cudatoolkit.

**Comment by Dejavusd** [comment]
> it seems there is something wrong with the environment, try to install or fix the cudatoolkit.

我conda install cudatoolkit后装的是11.3的版本，运行会报错
numba.cuda.cudadrv.driver.Linker Error: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR ptxas application ptx input, line 9; fatal : Unsupported .version 7.3; current version is '7.1'
是不是需要安装11.1的版本，怎么安装？
