### ISSUE TITLE
a question about ablation study 

### ISSUE THREAD

**Issue by jichaofeng** [xinzhuma/monodle#25]
We propose a method based on the monodle and need to do ablation study to evaluate the effect of our design. We obtain the different model when using the same code to train the network , so the detection results are vary largely. In this case, how to do the ablation study? Do you have a solution?  We train the model on a single GPU.

**Comment by xinzhuma** [comment]
不是很清楚你的意思，你是说两次实验之间的性能差异大？

**Comment by jichaofeng** [comment]
感谢你的回复。就是训练参数，训练周期都相同的情况下，用monodle的代码完整训练一次，得到的模型（比如都是训练70个周期后得到的），都会和上次得到的模型，测试出来的检测结果不一样，而且差别较大，说明学习到的模型不稳定。这说明我是在KITTI验证集上测试的，用的是单块GPU。我想如何解决这个问题，才能让每次学习出来的模型是一样的？这样才能在做消融实验时，确保得到的结果是改进模块起的作用，而不是模型的不稳定性造成的。

**Comment by xinzhuma** [comment]
相对来说，小batchsize会更不稳定一些，最好同步降低学习率。另外小batchsize可以尝试将dim_aware_loss换成l1 loss. 然后就是多次实验取平均。

**Comment by jichaofeng** [comment]
非常感谢你对我的帮助。

**Comment by jichaofeng** [comment]
感谢你的回复。就是训练参数，训练周期都相同的情况下，用monodle的代码完整训练一次，得到的模型（比如都是训练70个周期后得到的），都会和上次得到的模型，测试出来的检测结果不一样，而且差别较大，说明学习到的模型不稳定。这说明我是在KITTI验证集上测试的，用的是单块GPU。我想如何解决这个问题，才能让每次学习出来的模型是一样的？这样才能在做消融实验时，确保得到的结果是改进模块起的作用，而不是模型的不稳定性造成的。













在 2022-04-08 13:56:12，"XINZHU.MA" ***@***.***> 写道：

不是很清楚你的意思，你是说两次实验之间的性能差异大？
