### ISSUE TITLE
Does the provided pretrianed model only train on Car?

### ISSUE THREAD

**Issue by karenyun** [xinzhuma/monodle#26]
Hi, @xinzhuma 
Many thanks for the great work!
When I do the evaluation, it only tests on the Car. When I add the Pedestrian and Cyclist, the results are 0. 
So does the model only train on Car?

**Comment by xinzhuma** [comment]
yes, the pre-trained model is trained from the car instances

**Comment by karenyun** [comment]
@xinzhuma , Thanks for the quick reply!

Another thing is the 
`heatmap = np.zeros((self.num_classes, features_size[1], features_size[0]), dtype=np.float32) # C * H * W` in the line 178 of  
 kitti_dataset.py.

Why the size of heatmap is not `max_objs * num_class * feature_size[1] * feature_size[0]` ? 
Will the original setting fill all target samples of the same image in one heatmap?

**Comment by xinzhuma** [comment]
heatmap branch is trained for all feature positions, so it's shape is C*W*H. While other branches are only for the valid position [the positions which have objects], so their shapes are num_of_object * num_of_channels

**Comment by karenyun** [comment]
> heatmap branch is trained for all feature positions, so it's shape is C_W_H. While other branches are only for the valid position [the positions which have objects], so their shapes are num_of_object * num_of_channels
Got it!
Thanks!

**Comment by karenyun** [comment]
Sorry, @xinzhuma , I am still confused about the `num_classes=1000` in `class DLA`, where you do not reset the num_classes to 1 (for Car only) or 3 (For Car, Pedestrian, Cyclist). 
Could you give some reasons?

**Comment by xinzhuma** [comment]
the classification layer in DLA is removed, only the backbone part are used as feature extractors in monodle. It means that we build new classification (and regression) layers on DLA backbone.

**Comment by karenyun** [comment]
Many thanks!
