### ISSUE TITLE
Training config and log

### ISSUE THREAD

**Issue by AndersonStreedd** [xinzhuma/monodle#4]
Hi,

I cannot replicate the results in the paper using your paper's parameter. The performance is pretty low. Could you provide training logs and detailed config for reproducibility? Thanks!

**Comment by yama514** [comment]
Hi, 

Thanks for the great work. Is kitti_example.yaml the config file you use for the paper?

**Comment by xinzhuma** [comment]
Hi @yama514 , this repo is a little different from the code we use in the original paper, and I noticed the accuracy of this repo is unstable.  I update the code to make the performance stable and some new features have been added to achieve better performance.  @AndersonStreedd @yama514  you can try it now.

**Comment by yama514** [comment]
Thanks！
