### ISSUE TITLE
请问如何可视化预测结果，只得到txt，没得到预测图像

### ISSUE THREAD

**Issue by ShihuaiXu** [xinzhuma/monodle#6]
thanks for your grate work，请问如何可视化预测结果，只得到txt，没得到预测图像

**Comment by xinzhuma** [comment]
Hi, @ShihuaiXu  there is no visualization tool in this repo, while you can use this script 'https://github.com/xinzhuma/patchnet/blob/master/tools/visualization.py' for visualization.
