### ISSUE TITLE
请问关于远距离样本过滤，直接过滤不进行ignore处理，远距离样本不就当成负样本，这样不会有问题吗？

### ISSUE THREAD

**Issue by yjcn** [xinzhuma/monodle#9]
您好，感谢您的优秀工作。关于Training Samples这块有一些疑问，我看代码中是直接按照距离进行了过滤，并没有进行ignore处理
https://github.com/xinzhuma/monodle/blob/main/lib/datasets/kitti/kitti_dataset.py#L201
![image](https://user-images.githubusercontent.com/8858803/129152525-ceedd114-75f0-4096-8bfb-480103408337.png)

直接过滤不进行ignore处理，远距离样本不就当成负样本，这样不会有问题吗？

**Comment by xinzhuma** [comment]
关于这个问题，在heatmap branch确实是起到了负样本的作用，但其他branches中，因为mask的存在，并不会有这个问题。对于heatmap branch，这样的设计会使得远处的目标样本的confidence被压制，相比于ignore, 更有益于整体算法。

**Comment by yjcn** [comment]
@xinzhuma 好的 感谢您的回复，请问您这块是做过对比实验吗？在heatmap上不ignore远处目标，指标是比ignore远处目标好的？

**Comment by xinzhuma** [comment]
@yjcn 是的，我们在前期探索中做过类似实验

**Comment by yjcn** [comment]
@xinzhuma 好的 清楚了 感谢您的解答~
